version: '3.8'

services:
  chatbot:
    build: .
    ports:
      - "8000:8000"
      - "8100:8100"  # For Prometheus metrics
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./app:/app/app
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
